const riftCards = [
    "Someone gets a pentakill",
    "Racial slurs",
    "GG EZ",
    "Something in polish",
    "JG DIFF",
    "Baron",
    "Dragon steal",
    "Red/blue buff steal",
    "Level 7 mastery",
    "100k+ mastery points",
    "Everyone in a team is Level 5+ mastery",
    "Everyone has a skin",
    "Skin from the newest skin-line",
    "Yasuo/Yone level 7",
    "Threatening to AFK",
    "'Dont worry guys, I can carry'",
    "'Lets FF' / FF15",
    "Accusing someone of feeding",
    "Complaining about an op champ",
    "Complaining about an op item",
    "Complaining about a summoner spell"
];

const aramCards = [
    "Someone gets a pentakill",
    "Racial slurs",
    "GG EZ",
    "Something in polish",
    "Level 7 mastery",
    "100k+ mastery points",
    "Everyone in a team is Level 5+ mastery",
    "Everyone has a skin",
    "Skin from the newest skin-line",
    "Yasuo/Yone level 7",
    "Threatening to AFK",
    "'Dont worry guys, I can carry'",
    "'Lets FF' / FF15",
    "Accusing someone of feeding",
    "Complaining about an op champ",
    "Complaining about an op item",
    "Poro explodes in ARAM",
    "Complaining about a summoner spell"
];