const riftCards = [
    "Someone gets a pentakill",
    "Profanity",
    "Someone says 'GG EZ/EZ'",
    "Something in polish/french",
    "Someone says 'JG DIFF'",
    "Baron steal",
    "Dragon steal",
    "Red/blue buff steal",
    "Level 7 mastery",
    "100k+ mastery points",
    "Everyone in a team is Level 5+ mastery",
    "Everyone has a skin",
    "Skin from the newest skin-line",
    "Yasuo/Yone level 7",
    "Threatening to AFK",
    "Someone says 'Dont FF, I can carry'",
    "'Lets FF' / FF15",
    "Accusing someone of feeding",
    "Complaining about a champion",
    "Complaining about an item",
    "Complaining about a summoner spell",
    "Deal the most amount of damage",
    "Deal the least amount of damage",
    "Support outdamages ADC",
    "Someone saying 'Dont end'",
    "ADC has 0 kills while SUP has 3",
    "Matching nicknames",
    "Insulting nickname",
    "Teemo pick",
    "Emote spam",
    "Fail flash",
    "Fail ward",
    "Missed ultimate",
    "Spam ping",
    "Spam ping 'Enemy missing'",
    "Spam ping 'Bait'",
    "Executed",
    "Scuttle crab dodging skillshots",
    "BM-ing",
    "Off-meta build",
    "Perma split pusher",
    "Successful 1v3",
    "4 honors",
    "Questioning someone's play",
    "Level 1 fiesta",
    "Someone is autofilled",
    "Jungler taxing laner",
    "3 man bot dive"
];

const aramCards = [
    "Someone gets a pentakill",
    "Profanity",
    "Someone says 'GG EZ/EZ'",
    "Something in polish/french",
    "Level 7 mastery",
    "100k+ mastery points",
    "Everyone in a team is Level 5+ mastery",
    "Everyone has a skin",
    "Skin from the newest skin-line",
    "Yasuo/Yone level 7",
    "Threatening to AFK",
    "Someone says 'Dont FF, I can carry'",
    "'Lets FF' / FF15",
    "Accusing someone of feeding",
    "Complaining about a champion",
    "Complaining about an item",
    "Poro explodes in ARAM",
    "Complaining about a summoner spell",
    "Heal/Exhaust summoner spell",
    "Clarity/Cleanse summoner spell",
    "Everyone has the snowball spell",
    "Get dove 1v5 under your turret",
    "Deal the most amount of damage",
    "Deal the least amount of damage",
    "Someone saying 'Dont end'",
    "Matching nicknames",
    "Insulting nickname",
    "Teemo pick",
    "Emote spam",
    "Fail flash",
    "Missed ultimate",
    "Spam ping",
    "Spam ping 'Enemy missing'",
    "Spam ping 'Bait'",
    "Executed",
    "BM-ing",
    "Off-meta build",
    "Successful 1v3",
    "4 honors",
    "Questioning someone's play",
    "Someone is autofilled"
];